const { spawnSync } = require('child_process')
const { existsSync, writeFileSync } = require('fs')

const SESSION_ID = 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaUgyeE94TDdtcnloQ0xwOUVDQ1Y4VTZXZFpJcXlNdFdxNkUrMWQwckxucz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZHhyY3BPVkZnaStYRGpJaFJMQ1U4bTdCdWFVelh4bWFhQVZDQ0d4cDh5ND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBTk1XTjhlMisyT0ZHNHFrbk1XV3BUdVdEN1NySUNMdTJUdVRtdE42WVZ3PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ2WDcxamQ3Njdxcm1IZG00QUg2OWpJL3owTi9mV1N4K2xBMjB0ZEpsYVFzPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVFODIvbFNRTEFWZW5xWHp0dDRmMnpOTEdBdEpxbmk1TVF2SWZPVHBpRk09In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkpuVXZlbGNQNEgvcS8rdmhBdDdtT3VwdGFlMm1KVG5oTFZ4ekVINUhaa1U9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMEcwVTJ0RGVHWXFLWGRmSzNiZmJEcEFPYkszcG9yYnllUHRRcWdSNzEwZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSkRGRzVOS0o4dVgwT3J0Nm03ejlTUm10NDJqTUpxY25SQWJ0MzVMc2F4dz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ino5YmxsaS9Xd3QzNG9tTjNpekYwa1U4ZWlmanltbWNKK0NNckZLaXQxNjAxSi8xRk11SWUrc2FlQWh4c1JMOGxlT09hTnNvSU1zdkN4emlFZ0RMUmlRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NjcsImFkdlNlY3JldEtleSI6IlFETlluak1nVklMQ1VVSEYwTFdaN2hycmhaNnF0OFdkUXV1M3pManI4QWM9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3MTkyODQ4MjJAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQTBBM0UxQjFCNzg4OEZFNzc5MkRFQTlBRTY2MEMzNkUifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczMjIwMzY3N30seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3MTkyODQ4MjJAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQTExQUZFMzRFOTc0RkE4MUE4QjlGNTQ5NDM0MENGRkEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczMjIwMzY3N31dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiZ3dvOVRDZUNRYUdwZFJYT0NXcVBsdyIsInBob25lSWQiOiJmYTNkNTZmMy1kNzkwLTRkYjQtYmQ4MS00YWZlNDg3MjE1ZTQiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMmJ2ejkvOTViZDFaVE1iVkU3ZG5raWN5aVFRPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNtZCtRRHJ4N3l1ZWlleUNLeWFkNmovVFNQcz0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiI5RERGU0hUSCIsIm1lIjp7ImlkIjoiOTQ3MTkyODQ4MjI6MTFAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiX1/wnZmJ8J2ZgPCdmY3wnZmKX18ifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ056VXhOc0dFSTZwL2JrR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Inh1UUNKNlh1VDlGcUdLc3VoOXBmL0FVSkpKOWhjSEhIQ0ZMKzIzZ2h5VnM9IiwiYWNjb3VudFNpZ25hdHVyZSI6IktwMTN4YWNRSzAzK3UreElMRzA0Q2VnTHdrYWlYeUJPSFExdmFMSk44cjVEcXFZa3h4RmN6czdac1k1N3JwR1BYMElIN3luZU43U1d6blJjVzRkdUJBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJtYUNHQlgzMFpBaHg1R0thWkh5ZlFMVDgwaGFncS9od1A5bURKM2tla0srTG85ckNmQXJhaDd4bFVraGp1eUtsYmdLU0dRajdSaTlZeGVYNm9tK0JoZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6Ijk0NzE5Mjg0ODIyOjExQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmNia0FpZWw3ay9SYWhpckxvZmFYL3dGQ1NTZllYQnh4d2hTL3R0NEljbGIifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzIyMDM2NzUsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBTkFVIn0=' // Edit this line only, don't remove ' <- this symbol

if (!existsSync('Itxxwasi')) {
  console.log('Cloning the repository...')
  const cloneResult = spawnSync(
    'git',
    ['clone', 'https://github.com/Itxxwasi/WASI-MD-V.git', 'Itxxwasi'],
    {
      stdio: 'inherit',
    }
  )

  if (cloneResult.error) {
    throw new Error(`Failed to clone the repository: ${cloneResult.error.message}`)
  }

  const configPath = 'Itxxwasi/config.env'
  try {
    console.log('Writing to config.env...')
    writeFileSync(configPath, `VPS=true\nSESSION_ID=${SESSION_ID}`)
  } catch (err) {
    throw new Error(`Failed to write to config.env: ${err.message}`)
  }

  console.log('Installing dependencies...')
  const installResult = spawnSync('yarn', ['install', '--network-concurrency', '3'], {
    cwd: 'Itxxwasi',
    stdio: 'inherit',
  })

  if (installResult.error) {
    throw new Error(`Failed to install dependencies: ${installResult.error.message}`)
  }
}

spawnSync('yarn', ['start'], { cwd: 'Itxxwasi', stdio: 'inherit' })
